USER_SOFTWARE_ROOT="/usr/local/software"
JAVA_HOME=$USER_SOFTWARE_ROOT/jdk1.8.0_181
CLASSPATH=.:$JAVA_HOME/lib/
PATH=$PATH:$JAVA_HOME/bin
export PATH JAVA_HOME CLASSPATH

GRADLE_HOME=$USER_SOFTWARE_ROOT/gradle
GRADLE_USER_HOME=$GRADLE_HOME/.gradle
PATH=$PATH:$GRADLE_HOME/bin
export PATH GRADLE_HOME GRADLE_USER_HOME

MAVEN_HOME=$USER_SOFTWARE_ROOT/maven
M2_HOME=$MAVEN_HOME
PATH=$PATH:$MAVEN_HOME/bin
export PATH MAVEN_HOME M2_HOME

swr=$USER_SOFTWARE_ROOT
export swr

shr="/mnt/f/SHARE"
export shr

wpr="/usr/local/workspace"
export wpr
